name: Reddit Flat Finder

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run script
        env:
          MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
        run: python main.py
